### ISSUE TITLE
yum update before offline/online

### ISSUE THREAD

**Issue by neu5ron** [rocknsm/rock-docs#29]
If the box defaults to false offline in rocknsm config.yml then need to reorder/reorganized the flow in relation to performing a yum update but leaving the box to online_install: True..
recent issues showing this here:
https://community.rocknsm.io/t/trouble-with-automated-installation/124/9

**Comment by neu5ron** [comment]
also, place a mention/place-holder for suricata-update after build

**Comment by seven62** [comment]
@neu5ron all of these issues have been addressed thanks for the input!
