### ISSUE TITLE
fix ambiguity of generate default & deploy flow/wording

### ISSUE THREAD

**Issue by neu5ron** [rocknsm/rock-docs#32]
It can be a bit confusing to have the config mentioned before generate.
also, although some have probably understood to run the generate_defaults section before the deploy - it could make more sense to number these sections or mention explicitly that generate_defaults needs to be ran.
Because right now generate_defaults sections just says "So what happens when you've completely mucked things" and regards to "This script will regenerate a fresh default config.yml for you and get you out of jail. If you need to reset things you can execute this script by running:"

**Comment by seven62** [comment]
@neu5ron resolved with commit `e96dd73`
