### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by honey4free** [rocknsm/rock-docs#4]
Hi is there an easy clustering script or something ?.
One sensor is not always enough so easy deployment of multiple sensors with cross alert and sentral managment is an awsome thing to do.
We have alot of sensors

**Comment by dcode** [comment]
This is one of the next items to automate, but it isn't there yet. I typically feed multiple sensors into a Kafka cluster subject to the latency requirements of Kafka (i.e. don't span multiple datacenters). Then push multiple Kafka clusters into a large Elastic cloud.

The user uses a single Kibana instance. Is this what you had in mind?

**Comment by seven62** [comment]
Version 2.3 is being release today, with multi-node support.
