### ISSUE TITLE
Documentation has depreciated "Rockctl" section - confuses new users

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock-docs#59]
Should be corrected to "rock" command: 

https://docs.rocknsm.io/usage/#rockctl

Rockctl
The basic service management functions are accomplished with:
sudo rockctl status - get the status of ROCK services
sudo rockctl start - start ROCK services
sudo rockctl stop - stop ROCK services
sudo rockctl reset-failed - clear the failed states of services

**Comment by peasead** [comment]
No, `rockctl` is still the right command. While `rock status|start|stop` work, it's slower, not anywhere near as consumable, doesn't appear to include Docket, and `reset-failed` isn't included. 

`rockctl`. 
<img width="310" alt="RockNSM_2_5_1__Prepped_for_Analysis___Running_" src="https://user-images.githubusercontent.com/7442091/81430295-ccdb5d80-9124-11ea-8d78-0c345d2f46fc.png">

`rock status`
<img width="400" alt="RockNSM_2_5_1__Prepped_for_Analysis___Running_" src="https://user-images.githubusercontent.com/7442091/81431153-4d4e8e00-9126-11ea-92d7-d32577860fd4.png">
