### ISSUE TITLE
Failed to start Elasticsearch

### ISSUE THREAD

**Issue by pmzhou** [rocknsm/rock-docs#61]
FAILED! => {"changed": false, "msg": "Unable to start service elasticsearch: Job for elasticsearch.service failed because the control process exited with error code. See \"systemctl status elasticsearch.service\" and \"journalctl -xe\" for details.\n"

**What i get from journalctl -xe**

`-- Subject: Unit elasticsearch.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel`

`-- Unit elasticsearch.service has begun starting up.
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: output:
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: error:
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: Unrecognized VM option 'UseConcMarkSweepGC'
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: Error: Could not create the Java Virtual Machine.
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: Error: A fatal exception has occurred. Program will exit.
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:126)
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
Oct 18 12:33:23 rock01.rock.lan systemd-entrypoint[29741]: at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Oct 18 12:33:24 rock01.rock.lan systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Oct 18 12:33:24 rock01.rock.lan systemd[1]: Failed to start Elasticsearch.
-- Subject: Unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel`

**Comment by peasead** [comment]
Thanks for submitting the issue, @pmzhou 

Have you tried this: https://community.rocknsm.io/t/elasticsearch-service-fails-to-start/395

**Comment by pmzhou** [comment]
Hi

Thanks for the response. I finally managed to install it after making the following changes:
Comment out these lines in /usr/share/rock/roles/elasticsearch/templates/es-jvm.options.j2
a. #-XX: +UseConcMarkSweepGC
b. #-XX:CMSInitiatingOccupancyFraction=75
c. #=XX: +UseCMSInitiatingOccupancyOnly




________________________________
